ALTER TABLE exercises DROP COLUMN complete, ALTER COLUMN duration SET NOT NULL;
ALTER TABLE refluxs DROP COLUMN complete, ALTER COLUMN duration SET NOT NULL;
ALTER TABLE wees DROP COLUMN complete, ALTER COLUMN duration SET NOT NULL;
ALTER TABLE poos DROP COLUMN complete, ALTER COLUMN duration SET NOT NULL;
ALTER TABLE consumptions DROP COLUMN complete, ALTER COLUMN duration SET NOT NULL;
