ALTER TABLE wees
ADD COLUMN utc_offset INTEGER NOT NULL DEFAULT 39600;
ALTER TABLE poos
ADD COLUMN utc_offset INTEGER NOT NULL DEFAULT 39600;
ALTER TABLE consumptions
ADD COLUMN utc_offset INTEGER NOT NULL DEFAULT 39600;